### ISSUE TITLE
Alternative actions?

### ISSUE THREAD

**Issue by max-allan-surevine** [JamesFator/BTHSControl#5]
Hi, not really an issue, more of a feature request/question!

I'd like to remap one of my buttons to be a mic mute. I have a bit of applescript to set the mic volume  to 0 or 100 depending on whether it is already 100 or 0. But could I attach that to the button press code?
I'm guessing that the "if (status == 68)" bit in BTHSControlPlugin.m then calls
    HIDPostAuxKey(NX_KEYTYPE_PLAY); in BTHSInterface.m 
Can I easily make that jump out to an AppleScript instead or do I need to learn some cocoa ?

Thanks,
Max

**Comment by JamesFator** [comment]
Hey Max,

You can definitely change any of the code after that "if (status == 68)" line in BTHSControlPlugin.m to do whatever you want it to do.

I took a look into it and found out that running Applescript code is actually pretty easy, which means there's no need to dive into Objective-C. Check out the following method I used for testing:

```objc
- (void)toggleMute
{
    // Applescript command that returns "true" if volume is muted
    NSString *muteQueryCmd = @"output muted of (get volume settings)";
    // Applescript command that enables mute
    NSString *enableCmd = @"set volume with output muted";
    // Applescript command that disables mute
    NSString *disableCmd = @"set volume without output muted";
    
    // Test if mute is enabled using Applescript
    NSAppleScript *muteQuery = [[NSAppleScript alloc] initWithSource:muteQueryCmd];
    NSAppleEventDescriptor *isMuted = [muteQuery executeAndReturnError:nil];
    if ([[isMuted stringValue] isEqualToString:@"true"]) {
        // Mute is enabled, so disable it
        [[[NSAppleScript alloc] initWithSource:disableCmd] executeAndReturnError:nil];
    } else {
        // Mute is disabled, so enable it
        [[[NSAppleScript alloc] initWithSource:enableCmd] executeAndReturnError:nil];
    }
}
```

At the top is where I define the 3 Applescript commands we'll need. Then the two lines of code right above the IF statement execute an Applescript command. The first command we execute tests whether the system is currently muted. Then, if the system is muted, we execute the Applescript command "disableCMD", which will disable the mute and return the volume to where it was. If the system is not muted, it runs the Applescript command "enableCmd", which enabled the mute.

So you very well could paste this method right above the "playCommand" method in the BTHSControlPlugin.m file, then all you would need to do is replace the code after the "if (status == 68)" line with the call to our "toggleMute" method. It should look something like this:

```objc
- (void)playCommand:(int)status
{
    if (status == 68) {
        NSLog(@"BTHSCommand: Play Pressed");
        [self toggleMute];
    } else {
        NSLog(@"BTHSCommand: Play Released");
    }
}
```

...and I just realized you were talking about mic muting instead of system volume muting. Well it will work the same way! What you just need to do now is replace my 3 NSString definitions created above which mute the system and replace them with your own Applescript commands. If you don't have an Applescript command that tells you the current volume of the mic, you can create a variable for the class that will simply run the opposite command every time it's called.

Let me know if that worked for you!
