### ISSUE TITLE
how to remove?

### ISSUE THREAD

**Issue by walucks** [JamesFator/BTHSControl#6]
Hello James, 
for some reason BTHSControl is not working for me. I stupidly forgot to disconnect all bluetooth devices before installing. that might be the reason.
My first attempt would be to uninstall and try again, but i cannot figure out how to remove it.

Would be happy if you can help me out. It seems to be a great application.
Lukas

**Comment by JamesFator** [comment]
Hey walucks,
Sorry it took so long to respond. I added [this commit](https://github.com/JamesFator/BTHSControl/commit/707abcd775fde14e4415d86f84ac28f4a89b11d9) which gives you the option to remove the service. In your case, you can do that by running:
```bash
./install.sh uninstall old
```
(When you're in the BTHSControl directory in the Terminal app)

In terms of forgetting to disconnect the bluetooth devices, that's totally fine, it should work even after you install the service, simply by turning them off then reconnecting them again.

I'm going to close this because we have uninstall functionality, but if you continue to have issues getting this to work besides the removing part, you can create another issue, or feel free to email me, even if you have questions.
